# Generated by Django 5.1.6 on 2025-03-01 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectsubmission_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjusted amount agreed upon after dispute', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
