# Generated by Django 5.1.6 on 2025-03-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_proposal_final_amount_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='projects.proposal'),
        ),
    ]
